package UI_Battle_Pokemon;

import battle_pokemon.Batalha;
import battle_pokemon.Pokemon;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class UI_Batalha extends javax.swing.JFrame {
    
    Batalha batalha = new Batalha();
    
    Pokemon outropokemon = new Pokemon("Mewtow", "Psíquico");

    public UI_Batalha() {
        initComponents();
        
        img_outropokemon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Mewtwo.png"))); 
        dados_outroPoke.setText(outropokemon.imprimiPokemon());
        
         setExtendedState(JFrame.MAXIMIZED_BOTH);
    }
    
 public Icon icon(String path, int width, int heigth) {
        Icon img = new ImageIcon(new ImageIcon(getClass().getResource(path)).getImage()
                .getScaledInstance(width, heigth, java.awt.Image.SCALE_SMOOTH));
        return img;
}

    
public void enviaDados(UI_EscolhaSeuPokemon nome, Pokemon pokemon){
        String nomepoke =  pokemon.getNome(); 
        int vida = pokemon.getVida();
        
         batalha.meuPokemon(nomepoke, vida);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_tituloTela = new javax.swing.JLabel();
        img_outropokemon = new javax.swing.JLabel();
        img_pokemon = new javax.swing.JLabel();
        txt_tituloOutroPoke = new javax.swing.JLabel();
        txt_tituloSeuPoke = new javax.swing.JLabel();
        btn_start = new javax.swing.JButton();
        btn_fechar = new javax.swing.JLabel();
        dados_poke = new javax.swing.JLabel();
        dados_outroPoke = new javax.swing.JLabel();
        img_Fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        txt_tituloTela.setFont(new java.awt.Font("Consolas", 0, 48)); // NOI18N
        txt_tituloTela.setForeground(new java.awt.Color(255, 255, 255));
        txt_tituloTela.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_tituloTela.setText("Vamos a batalha !");
        getContentPane().add(txt_tituloTela);
        txt_tituloTela.setBounds(720, 60, 490, 57);

        img_outropokemon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(img_outropokemon);
        img_outropokemon.setBounds(1180, 400, 510, 450);

        img_pokemon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(img_pokemon);
        img_pokemon.setBounds(230, 410, 510, 450);

        txt_tituloOutroPoke.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        txt_tituloOutroPoke.setForeground(new java.awt.Color(255, 255, 255));
        txt_tituloOutroPoke.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txt_tituloOutroPoke.setText("Outro Pokemon: ");
        txt_tituloOutroPoke.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(txt_tituloOutroPoke);
        txt_tituloOutroPoke.setBounds(1020, 220, 200, 40);

        txt_tituloSeuPoke.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        txt_tituloSeuPoke.setForeground(new java.awt.Color(255, 255, 255));
        txt_tituloSeuPoke.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txt_tituloSeuPoke.setText("Seu Pokemon: ");
        txt_tituloSeuPoke.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        txt_tituloSeuPoke.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(txt_tituloSeuPoke);
        txt_tituloSeuPoke.setBounds(100, 220, 200, 40);

        btn_start.setBackground(new java.awt.Color(230, 65, 16));
        btn_start.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        btn_start.setText("START");
        btn_start.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        btn_start.setBorderPainted(false);
        btn_start.setFocusPainted(false);
        btn_start.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_start.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_startMouseClicked(evt);
            }
        });
        btn_start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_startActionPerformed(evt);
            }
        });
        getContentPane().add(btn_start);
        btn_start.setBounds(910, 940, 190, 50);

        btn_fechar.setFont(new java.awt.Font("sansserif", 0, 48)); // NOI18N
        btn_fechar.setForeground(new java.awt.Color(255, 255, 255));
        btn_fechar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_fechar.setText("X");
        btn_fechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_fecharMouseClicked(evt);
            }
        });
        getContentPane().add(btn_fechar);
        btn_fechar.setBounds(1840, 10, 40, 60);

        dados_poke.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        dados_poke.setForeground(new java.awt.Color(255, 255, 255));
        dados_poke.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dados_poke.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(dados_poke);
        dados_poke.setBounds(100, 280, 870, 40);

        dados_outroPoke.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        dados_outroPoke.setForeground(new java.awt.Color(255, 255, 255));
        dados_outroPoke.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dados_outroPoke.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(dados_outroPoke);
        dados_outroPoke.setBounds(1010, 280, 820, 40);

        img_Fundo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        img_Fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/TelaFundo_Escolha.png"))); // NOI18N
        getContentPane().add(img_Fundo);
        img_Fundo.setBounds(0, 0, 2000, 1289);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_fecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_fecharMouseClicked
         UI_TelaInicio telaIni = new UI_TelaInicio();
         telaIni.setVisible(true);
         
         dispose();
    }//GEN-LAST:event_btn_fecharMouseClicked

    private void btn_startMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_startMouseClicked
         batalha.outroPokemon(outropokemon.getNome(), outropokemon.getVida());
         
        JOptionPane.showMessageDialog(null, batalha.startBattle(), "A batalha vai começar!", JOptionPane.PLAIN_MESSAGE, icon("/img/pokebola.png", 60, 60));
    }//GEN-LAST:event_btn_startMouseClicked

    private void btn_startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_startActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_startActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI_Batalha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI_Batalha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI_Batalha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI_Batalha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI_Batalha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_fechar;
    private javax.swing.JButton btn_start;
    public javax.swing.JLabel dados_outroPoke;
    public javax.swing.JLabel dados_poke;
    private javax.swing.JLabel img_Fundo;
    public javax.swing.JLabel img_outropokemon;
    public javax.swing.JLabel img_pokemon;
    private javax.swing.JLabel txt_tituloOutroPoke;
    public javax.swing.JLabel txt_tituloSeuPoke;
    private javax.swing.JLabel txt_tituloTela;
    // End of variables declaration//GEN-END:variables
}
